services:
  phpmyadmin-web:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
      args:
        - PHPMYADMIN_VERSION
        - buildno
        - gitcommithash
    image: phpmyadmin-frankenphp:local
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    volumes:
      - ${DATA_DIR:-./data}/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

volumes:
  caddy_data:
  caddy_config:
