services:
  phpmyadmin-web:
    image: ghcr.io/mapiiik/phpmyadmin-frankenphp:latest
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      LISTENER_MODE: ${LISTENER_MODE:-direct}
      PROXY_ALLOW: ${PROXY_ALLOW:-127.0.0.1/32 ::1/128}
    volumes:
      - ${DATA_DIR:-./data}/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

volumes:
  caddy_data:
  caddy_config:
